# POSTTEST 4

#### Nama : Hendy Saputra

#### NIM  : 2109106120

#### Informatika C1'21

#### link dataset:  https://drive.google.com/drive/folders/1wBDLkhNzPTigzDJITYwsJroWSHSAeB49?usp=drive_link¶

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

# Info Data

In [35]:
df = pd.read_csv('winemag-data-130k-v2.csv')
df

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             129971 non-null  int64
 1   country                129908 non-null  object
 2   description            129971 non-null  object
 3   designation            92506 non-null   object
 4   points                 129971 non-null  int64
 5   price                  120975 non-null  float64
 6   province               129908 non-null  object
 7   region_1               108724 non-null  object
 8   region_2               50511 non-null   object
 9   taster_name            103727 non-null  object
 10  taster_twitter_handle  98758 non-null   object
 11  title                  129971 non-null  object
 12  variety                129970 non-null  object
 13  winery                 129971 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 13.9+ MB

In [3]:
df.shape

(129971, 14)

## Membagi dataset menjadi training set dan testing set dengan proporsi 70:30

In [5]:
X = df.iloc[:, : -1]
y = df.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print("Dimensi X_train", X_train.shape)
print("Dimensi X_test", X_test.shape)
print("Dimensi y_train", y_train.shape)
print("Dimensi y_test", y_test.shape)

Dimensi X_train (90979, 13)
Dimensi X_test (38992, 13)
Dimensi y_train (90979,)
Dimensi y_test (38992,)

## Lakukan normalisasi data pada salah satu attribute menggunakan Min Max scaler (buatlah copy dataset terlebih dahulu)

In [20]:
min_max = MinMaxScaler()

# Copy Data
copy1 = df
dataCopy_normalization = copy1[["points"]]

normalization = min_max.fit_transform(dataCopy_normalization[["points"]])

df_normalization = pd.DataFrame(normalization)
df_normalization.columns =["points_Normalization"]

dataCopy_normalization = dataCopy_normalization.join(df_normalization["points_Normalization"]).reset_index()
dataCopy_normalization = dataCopy_normalization.drop("index", axis=1)

print()
print("Data Sebelum dan Sesudah dilakukan normalisasi : \n")
dataCopy_normalization.head(10)

Data Sebelum dan Sesudah dilakukan normalisasi :

   points  points_Normalization
0      87                  0.35
1      87                  0.35
2      87                  0.35
3      87                  0.35
4      87                  0.35
5      87                  0.35
6      87                  0.35
7      87                  0.35
8      87                  0.35
9      87                  0.35

## Lakukan standarisasi pada dataset (buatlah copy dataset terlebih dahulu)

In [34]:

# Membuat salinan dataset
data_copy = df.copy()

# memilih atribut yang ingin di standarisasi
attribute_to_standardize = 'points'

# Inisialisasi StandardScaler
scaler = StandardScaler()

# Standarisasi atribut
data_copy[attribute_to_standardize] = scaler.fit_transform(data_copy[[attribute_to_standardize]])

# Menampilkan atribut 'points' sebelum dan sesudah standarisasi
print("Atribut 'points' Sebelum dan Sesudah Standarisasi:\n")
print("Sebelum Standarisasi:\n")
print(data[[attribute_to_standardize]].head(10))
print("\nSesudah Standarisasi:\n")
print(data_copy[[attribute_to_standardize]].head(10))

Atribut 'points' Sebelum dan Sesudah Standarisasi:

Sebelum Standarisasi:

   points
0      87
1      87
2      87
3      87
4      87
5      87
6      87
7      87
8      87
9      87

Sesudah Standarisasi:

     points
0 -0.476076
1 -0.476076
2 -0.476076
3 -0.476076
4 -0.476076
5 -0.476076
6 -0.476076
7 -0.476076
8 -0.476076
9 -0.476076

## Lakukan Data cleaning pada data dengan nilai null (jika tidak ada nilai null pada dataset, maka buatlah menjadi ada). Ganti nilai null sesuai ketentuan. (bilangan bulat : median/modus, bilangan desimal : mean, tulisan : modus).

## Nilai Null

In [32]:
df.isna().sum()

Unnamed: 0                   0
country                     63
description                  0
designation              37465
points                       0
price                     8996
province                    63
region_1                 21247
region_2                 79460
taster_name              26244
taster_twitter_handle    31213
title                        0
variety                      1
winery                       0
dtype: int64

In [69]:
# menghapus atribut nilai null
df.dropna(inplace=True) 
df.isna().sum()

Unnamed: 0               0
country                  0
description              0
designation              0
points                   0
price                    0
province                 0
region_1                 0
region_2                 0
taster_name              0
taster_twitter_handle    0
title                    0
variety                  0
winery                   0
dtype: int64

### Mengubah bilangan bulat menjadi median/modus

In [79]:
data = pd.read_csv('winemag-data-130k-v2.csv')
strategi1 = SimpleImputer(strategy="median")

data["points"] = strategi1.fit_transform(data[["points"]])

data.isna().sum()

Unnamed: 0                   0
country                     63
description                  0
designation              37465
points                       0
price                     8996
province                    63
region_1                 21247
region_2                 79460
taster_name              26244
taster_twitter_handle    31213
title                        0
variety                      1
winery                       0
dtype: int64

### Mengubah bilangan desimal menjadi mean

In [4]:
import pandas as pd
data = pd.read_csv('winemag-data-130k-v2.csv')
from sklearn.impute import SimpleImputer
strategi2 = SimpleImputer(strategy="mean")

data["price"] = strategi2.fit_transform(data[["price"]])

data.isna().sum()

Unnamed: 0                   0
country                     63
description                  0
designation              37465
points                       0
price                        0
province                    63
region_1                 21247
region_2                 79460
taster_name              26244
taster_twitter_handle    31213
title                        0
variety                      1
winery                       0
dtype: int64

### Mengubah tulisan menjadi modus

In [8]:
import pandas as pd
data = pd.read_csv('winemag-data-130k-v2.csv')
# Daftar kolom yang akan diisi dengan modus
kolom_tulisan = ['country','price', 'designation', 'province', 'region_1', 'region_2', 'taster_name', 'taster_twitter_handle','variety']

# Loop melalui kolom-kolom tersebut dan ganti nilai null dengan modus
for kolom in kolom_tulisan:
    modus = data[kolom].mode()[0]  # Mengambil modus kolom
    data[kolom].fillna(modus, inplace=True)

data.isna().sum()

Unnamed: 0               0
country                  0
description              0
designation              0
points                   0
price                    0
province                 0
region_1                 0
region_2                 0
taster_name              0
taster_twitter_handle    0
title                    0
variety                  0
winery                   0
dtype: int64

## cleaning duplicate

In [14]:
data[data.duplicated()]

print("Jumlah Data Duplikat : ")
data.duplicated().sum()

Jumlah Data Duplikat :

0

### Karena tidak ada data nilai duplikat maka membuat nilai duplikat

In [16]:
make_duplicated = pd.concat([data]*2, ignore_index=True)
make_duplicated.duplicated()

print("Jumlah data duplicated sekarang :")
make_duplicated.duplicated().sum()

Jumlah data duplicated sekarang :

129971

In [17]:
make_duplicated.drop_duplicates(inplace=True)

hasil = make_duplicated.reset_index(drop=True)
print("Jumlah data duplicated setelah di drop :")
hasil.duplicated().sum()

Jumlah data duplicated setelah di drop :

0

## Ganti tipe data salah satu attribute angka

In [ ]:
print("Tipe data points sebelum diubah :")
df["points"].dtypes

In [19]:
ubah_dtype = data["points"].astype("float")
print("Tipe data points setelah diubah :")
ubah_dtype.dtypes

Tipe data points setelah diubah :

dtype('float64')

## Lakukan one hot encoding pada dataset yang kalian miliki

In [38]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Memuat dataset
data = pd.read_csv('winemag-data-130k-v2.csv')

# Inisialisasi OneHotEncoder
one_hot = OneHotEncoder(sparse=False, drop='first')  # drop='first' menghapus kategori pertama untuk menghindari multicollinearity

# Melakukan one-hot encoding pada kolom 'country'
df_onehot = one_hot.fit_transform(data[['country']])

# Membuat DataFrame dari hasil encoding
df_encoded = pd.DataFrame(df_onehot, columns=one_hot.get_feature_names(['country']))

# Menggabungkan hasil encoding ke dalam dataset asli
data = pd.concat([data, df_encoded], axis=1)

# Hapus kolom 'country' asli yang telah di-one-hot-encoded
data.drop(['country'], axis=1, inplace=True)

# Menampilkan hasil
data.head(10)

,Unnamed: 0,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,...,country_Slovakia,country_Slovenia,country_South Africa,country_Spain,country_Switzerland,country_Turkey,country_US,country_Ukraine,country_Uruguay,country_nan
0,0,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,3,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,4,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5,5,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6,6,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,7,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,8,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,9,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0